resolver: lts-10.0

packages:
- coinmetrics
- coinmetrics-ethereum
- coinmetrics-export

extra-deps:
#- avro-0.2.0.0
- git: https://github.com/LeifW/avro.git
  commit: bf1dcd3d663022afa4aa6bcecd2752cb807cb06e
- pure-zlib-0.6
- diskhash-0.0.4.0
- git: https://github.com/quyse/hanalytics.git
  commit: 8cd4e866670ecc1bbafcb88c0c847fe547b9e7da
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres

ghc-options:
  "$locals": -threaded -Wall -Wno-tabs
